apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tapflow

resources:
  - deploy/k8s/statefulset.yaml
  - deploy/k8s/service.yaml
  - deploy/k8s/service-agent-nodeport.yaml
  - deploy/k8s/ingress.yaml
