apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tapflow-relay
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ios.clab.one
      secretName: tapflow-relay-tls
  rules:
    - host: ios.clab.one
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tapflow-relay
                port:
                  number: 80
